language: node_js
node_js:
  - '8'
install:
  - npm install -g ganache-cli truffle
  - npm install
  - truffle migrate
  - npm link # ganache-snapshot needs to be installed to test plugin functionality
before_script:
  - ganache-cli > /dev/null &
script:
  - npm run lint
  - truffle test
  - ./test/cli/e2e.sh
